/**
 * Traffic monitoring keepalive daemon primitives
 * 
 * This module provides utilities for creating and managing a daemon that
 * monitors sudocode server activity and keeps the codespace alive by
 * executing SSH commands to self.
 * 
 * The daemon works by:
 * 1. Monitoring the sudocode server log file for modifications
 * 2. Executing SSH commands to self every N seconds (while active)
 * 3. Tracking time since last log activity
 * 4. Stopping SSH commands when keepalive duration expires
 * 5. Resuming SSH commands if activity restarts after expiry
 * 
 * This keeps the codespace alive by maintaining active SSH sessions,
 * preventing GitHub's idle timeout from pausing the codespace.
 */

import { execInCodespace } from './execution.js';
import type { TrafficMonitorOptions } from './types.js';

/**
 * Generate bash script for traffic monitoring daemon
 * 
 * The generated script:
 * - Monitors the server log file for modifications
 * - Tracks the last time activity was detected
 * - Executes SSH commands to self every N seconds (default: 30)
 * - Stops SSH commands after keepalive duration expires
 * - Resumes SSH commands if activity restarts after expiry
 * - Uses PID file for process management
 * - Requires login shell to access gh CLI
 * 
 * The script is designed to be portable and work on both Linux and macOS
 * stat commands (using -c for Linux and -f for macOS).
 * 
 * @param options - Traffic monitor configuration
 * @returns Bash script content as string
 * 
 * @example
 * ```typescript
 * const script = generateDaemonScript({
 *   codespaceName: 'my-codespace-abc123',
 *   serverPort: 3000,
 *   serverLogPath: '/tmp/sudocode-3000.log',
 *   keepAliveHours: 24,
 *   sshIntervalMinutes: 0.5
 * });
 * // Returns: "#!/bin/bash -l\n# Traffic monitoring keepalive daemon..."
 * ```
 */
function generateDaemonScript(options: TrafficMonitorOptions): string {
  const {
    codespaceName,
    serverPort,
    serverLogPath,
    keepAliveHours,
    sshIntervalMinutes = 0.5
  } = options;
  
  // Convert to integers to avoid bash arithmetic issues
  // Ensure we have valid numbers, default to safe values if not
  const keepAliveSeconds = Math.floor((keepAliveHours || 24) * 3600);
  const sshIntervalSeconds = Math.floor((sshIntervalMinutes || 0.5) * 60);
  
  // Debug logging
  console.log(`[generateDaemonScript] Input: keepAliveHours=${keepAliveHours}, sshIntervalMinutes=${sshIntervalMinutes}`);
  console.log(`[generateDaemonScript] Calculated: keepAliveSeconds=${keepAliveSeconds}, sshIntervalSeconds=${sshIntervalSeconds}`);
  
  // Validate that we got valid positive integers
  if (keepAliveSeconds <= 0 || sshIntervalSeconds <= 0) {
    throw new Error(`Invalid keepalive parameters: keepAliveHours=${keepAliveHours}, sshIntervalMinutes=${sshIntervalMinutes}`);
  }
  
  return `#!/bin/bash -l
# Traffic monitoring keepalive daemon for sudocode server
# Generated by sudopod
#
# This daemon monitors server log activity and executes SSH commands to self
# to keep the codespace alive. It stops SSH commands after the keepalive
# duration expires, but resumes if activity restarts.
#
# IMPORTANT: Must run as login shell (#!/bin/bash -l) to access gh CLI

# Enable strict mode (but not -e, as functions return non-zero by design)
set -u

CODESPACE_NAME="${codespaceName}"
SERVER_LOG="${serverLogPath}"
KEEPALIVE_SECONDS=${keepAliveSeconds}
SSH_INTERVAL=${sshIntervalSeconds}
DAEMON_PID_FILE="/tmp/sudocode-monitor-${serverPort}.pid"
DAEMON_LOG="/tmp/sudocode-monitor-${serverPort}-daemon.log"

# Log function for debugging
log() {
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*" >> "$DAEMON_LOG"
}

# Write our PID for process management
echo $$ > "$DAEMON_PID_FILE"
log "Daemon started with PID \$\$"
log "Codespace: \$CODESPACE_NAME"
log "Keepalive: \$KEEPALIVE_SECONDS seconds, SSH interval: \$SSH_INTERVAL seconds"

# Initialize last activity time to the log file's current mtime
# If log file doesn't exist yet, use current time
if [ -f "$SERVER_LOG" ]; then
  last_activity=$(stat -c %Y "$SERVER_LOG" 2>/dev/null || stat -f %m "$SERVER_LOG" 2>/dev/null || echo "0")
  # Fallback to current time if stat failed
  if [ "$last_activity" = "0" ]; then
    last_activity=$(date +%s)
    log "Could not read log file mtime, initialized to current time: \$last_activity"
  else
    log "Initialized from log file mtime: \$last_activity"
  fi
else
  last_activity=$(date +%s)
  log "Log file not found, initialized to current time: \$last_activity"
fi

# Function to check for new log activity
# Returns 0 if activity detected, 1 otherwise
check_activity() {
  if [ -f "$SERVER_LOG" ]; then
    # Get the last modified time of the log file
    # Try Linux stat first (-c), fall back to macOS stat (-f)
    local log_mtime=$(stat -c %Y "$SERVER_LOG" 2>/dev/null || stat -f %m "$SERVER_LOG" 2>/dev/null || echo "0")
    
    # Only update if we got a valid mtime
    if [ "$log_mtime" != "0" ] && [ "$log_mtime" -gt "$last_activity" ]; then
      last_activity="$log_mtime"
      return 0  # Activity detected
    fi
  fi
  return 1  # No activity
}

# Main monitoring loop
log "Entering monitoring loop"
while true; do
  current_time=$(date +%s)
  
  # Check for new activity (updates last_activity if found)
  if check_activity; then
    log "Activity detected! Updated last_activity to \$last_activity"
  fi
  
  # Calculate time since last activity
  time_since_activity=$((current_time - last_activity))
  
  # If we're within the keepalive window, execute SSH command
  if [ "$time_since_activity" -lt "$KEEPALIVE_SECONDS" ]; then
    # Execute SSH to self to keep codespace alive
    if gh codespace ssh -c "\$CODESPACE_NAME" -- 'echo "keepalive"' >> "$DAEMON_LOG" 2>&1; then
      log "SSH keepalive executed successfully (time since activity: \${time_since_activity}s / \${KEEPALIVE_SECONDS}s)"
    else
      log "SSH keepalive failed (time since activity: \${time_since_activity}s / \${KEEPALIVE_SECONDS}s)"
    fi
  else
    log "Keepalive expired (time since activity: \${time_since_activity}s / \${KEEPALIVE_SECONDS}s), skipping SSH"
  fi
  
  # Sleep until next SSH interval
  sleep "$SSH_INTERVAL"
done
`;
}

/**
 * Start traffic monitoring daemon in codespace
 * 
 * This function:
 * 1. Generates the daemon bash script with SSH keepalive logic
 * 2. Writes script directly to codespace via SSH using base64 encoding
 * 3. Makes it executable
 * 4. Starts it in the background with nohup in a LOGIN SHELL
 * 5. Verifies the daemon started by checking for PID file
 * 
 * IMPORTANT: The daemon must run in a login shell (bash -l) to have
 * access to the gh CLI, which is required for SSH-to-self keepalive.
 * 
 * The daemon runs independently in the codespace and continues monitoring
 * until explicitly stopped with `stopTrafficMonitor()`.
 * 
 * @param options - Traffic monitor configuration
 * @throws Error if daemon fails to start or PID file not created
 * 
 * @example
 * ```typescript
 * await startTrafficMonitor({
 *   codespaceName: 'my-codespace-abc123',
 *   serverPort: 3000,
 *   serverLogPath: '/tmp/sudocode-3000.log',
 *   keepAliveHours: 24,
 *   sshIntervalMinutes: 0.5
 * });
 * console.log('Traffic monitor daemon started');
 * ```
 */
export async function startTrafficMonitor(
  options: TrafficMonitorOptions
): Promise<void> {
  const { codespaceName, serverPort } = options;
  
  // 1. Generate daemon script
  const scriptContent = generateDaemonScript(options);
  
  // Debug: Log the script content to help diagnose issues
  console.log(`\nGenerated daemon script for port ${serverPort}:`);
  console.log('---START SCRIPT---');
  console.log(scriptContent);
  console.log('---END SCRIPT---\n');
  
  // 2. Write script directly to codespace via SSH using base64 encoding to avoid heredoc issues
  const remoteScriptPath = `/tmp/sudocode-monitor-${serverPort}.sh`;
  
  // Encode script content as base64 to safely transmit through SSH
  const scriptBase64 = Buffer.from(scriptContent).toString('base64');
  
  await execInCodespace(
    codespaceName,
    `echo '${scriptBase64}' | base64 -d > ${remoteScriptPath}`,
    { streamOutput: false, timeout: 10000 }
  );
  
  // 3. Make executable
  await execInCodespace(
    codespaceName,
    `chmod +x ${remoteScriptPath}`,
    { streamOutput: false, timeout: 5000 }
  );
  
  // 4. Start daemon in background using LOGIN SHELL (bash -l) to access gh CLI
  // The daemon script itself has #!/bin/bash -l shebang, but we also need to
  // start it in a login shell to ensure gh CLI is available
  // 
  // IMPORTANT: Use background: true option to ensure process persists after SSH disconnect
  // Note: Don't redirect nohup output - the script handles its own logging
  await execInCodespace(
    codespaceName,
    `nohup ${remoteScriptPath} >/dev/null 2>&1 </dev/null &`,
    { streamOutput: false, timeout: 10000, background: true }
  );
  
  // 5. Verify daemon is running (check for PID file)
  // Give it a moment to start and write PID file
  await new Promise(resolve => setTimeout(resolve, 2000));
  
  const pidFileExists = await execInCodespace(
    codespaceName,
    `test -f /tmp/sudocode-monitor-${serverPort}.pid && echo "1" || echo "0"`,
    { streamOutput: false }
  );
  
  if (pidFileExists.trim() !== '1') {
    // Get daemon log to help debug
    let daemonLog = '';
    try {
      daemonLog = await execInCodespace(
        codespaceName,
        `cat /tmp/sudocode-monitor-${serverPort}-daemon.log 2>&1 || echo "No log file"`,
        { streamOutput: false }
      );
    } catch (e) {
      daemonLog = 'Could not read daemon log';
    }
    
    throw new Error(`Traffic monitor daemon failed to start: PID file not created\nDaemon log:\n${daemonLog}`);
  }
}

/**
 * Stop traffic monitoring daemon in codespace
 * 
 * Reads the daemon's PID from its PID file and sends a kill signal.
 * Cleans up the PID file after stopping the daemon.
 * 
 * If the daemon is not running or PID file doesn't exist, this function
 * succeeds silently (idempotent operation).
 * 
 * @param codespaceName - Codespace name
 * @param serverPort - Server port number
 * 
 * @example
 * ```typescript
 * await stopTrafficMonitor('my-codespace-abc123', 3000);
 * console.log('Traffic monitor daemon stopped');
 * ```
 */
export async function stopTrafficMonitor(
  codespaceName: string,
  serverPort: number
): Promise<void> {
  const pidFile = `/tmp/sudocode-monitor-${serverPort}.pid`;
  
  // Read PID and kill process, remove PID file
  // Use || true to make the command succeed even if process doesn't exist
  await execInCodespace(
    codespaceName,
    `[ -f ${pidFile} ] && kill $(cat ${pidFile}) && rm ${pidFile} || true`,
    { streamOutput: false }
  );
}

/**
 * Check if traffic monitor is running
 * 
 * Checks both that:
 * 1. The PID file exists
 * 2. The process is actually running (via `ps -p <pid>`)
 * 
 * This ensures we detect stale PID files where the daemon has crashed
 * or been killed externally.
 * 
 * @param codespaceName - Codespace name
 * @param serverPort - Server port number
 * @returns True if daemon is running, false otherwise
 * 
 * @example
 * ```typescript
 * const isRunning = await isTrafficMonitorRunning('my-codespace-abc123', 3000);
 * if (isRunning) {
 *   console.log('Traffic monitor is active');
 * } else {
 *   console.log('Traffic monitor is not running');
 * }
 * ```
 */
export async function isTrafficMonitorRunning(
  codespaceName: string,
  serverPort: number
): Promise<boolean> {
  try {
    const pidFile = `/tmp/sudocode-monitor-${serverPort}.pid`;
    
    // Check if PID file exists and contains a valid PID
    // Then check if that process is running
    // Use 'if' statement for clearer logic than chained && ||
    const result = await execInCodespace(
      codespaceName,
      `if [ -f ${pidFile} ]; then pid=$(cat ${pidFile}); if ps -p "$pid" >/dev/null 2>&1; then echo "1"; else echo "0"; fi; else echo "0"; fi`,
      { streamOutput: false }
    );
    
    return result.trim() === '1';
  } catch (error) {
    // If command fails (e.g., codespace unreachable), assume not running
    return false;
  }
}
