/**
 * Traffic monitoring keepalive daemon primitives
 * 
 * This module provides utilities for creating and managing a daemon that
 * monitors sudocode server activity and keeps the codespace alive by
 * writing periodic heartbeats to a file.
 * 
 * The daemon works by:
 * 1. Monitoring the sudocode server log file for modifications
 * 2. Writing heartbeats to a file every N minutes (while active)
 * 3. Tracking time since last log activity
 * 4. Stopping heartbeats when keepalive duration expires
 * 5. Resuming heartbeats if activity restarts after expiry
 * 
 * This keeps the codespace alive by ensuring regular filesystem activity,
 * preventing GitHub's idle timeout from pausing the codespace.
 */

import { execInCodespace } from './execution.js';
import type { TrafficMonitorOptions } from './types.js';

/**
 * Generate bash script for traffic monitoring daemon
 * 
 * The generated script:
 * - Monitors the server log file for modifications
 * - Tracks the last time activity was detected
 * - Writes heartbeats every N minutes (default: 1)
 * - Stops heartbeats after keepalive duration expires
 * - Resumes heartbeats if activity restarts after expiry
 * - Uses PID file for process management
 * 
 * The script is designed to be portable and work on both Linux and macOS
 * stat commands (using -c for Linux and -f for macOS).
 * 
 * @param options - Traffic monitor configuration
 * @returns Bash script content as string
 * 
 * @example
 * ```typescript
 * const script = generateDaemonScript({
 *   serverPort: 3000,
 *   serverLogPath: '/tmp/sudocode-3000.log',
 *   keepAliveHours: 24,
 *   heartbeatIntervalMinutes: 1
 * });
 * // Returns: "#!/bin/bash\n# Traffic monitoring keepalive daemon..."
 * ```
 */
function generateDaemonScript(options: TrafficMonitorOptions): string {
  const {
    serverPort,
    serverLogPath,
    keepAliveHours,
    heartbeatIntervalMinutes = 1
  } = options;
  
  const heartbeatPath = `/tmp/keepalive-heartbeat-${serverPort}.txt`;
  // Convert to integers to avoid bash arithmetic issues
  // Ensure we have valid numbers, default to safe values if not
  const keepAliveSeconds = Math.floor((keepAliveHours || 24) * 3600);
  const heartbeatIntervalSeconds = Math.floor((heartbeatIntervalMinutes || 1) * 60);
  
  // Debug logging
  console.log(`[generateDaemonScript] Input: keepAliveHours=${keepAliveHours}, heartbeatIntervalMinutes=${heartbeatIntervalMinutes}`);
  console.log(`[generateDaemonScript] Calculated: keepAliveSeconds=${keepAliveSeconds}, heartbeatIntervalSeconds=${heartbeatIntervalSeconds}`);
  
  // Validate that we got valid positive integers
  if (keepAliveSeconds <= 0 || heartbeatIntervalSeconds <= 0) {
    throw new Error(`Invalid keepalive parameters: keepAliveHours=${keepAliveHours}, heartbeatIntervalMinutes=${heartbeatIntervalMinutes}`);
  }
  
  return `#!/bin/bash
# Traffic monitoring keepalive daemon for sudocode server
# Generated by sudopod
#
# This daemon monitors server log activity and writes periodic heartbeats
# to keep the codespace alive. It stops writing heartbeats after the
# keepalive duration expires, but resumes if activity restarts.

SERVER_LOG="${serverLogPath}"
HEARTBEAT_FILE="${heartbeatPath}"
KEEPALIVE_SECONDS=${keepAliveSeconds}
HEARTBEAT_INTERVAL=${heartbeatIntervalSeconds}
DAEMON_PID_FILE="/tmp/sudocode-monitor-${serverPort}.pid"

# Write our PID for process management
echo $$ > "$DAEMON_PID_FILE"

# Initialize last activity time to now
last_activity=$(date +%s)

# Function to check for new log activity
# Returns 0 if activity detected, 1 otherwise
check_activity() {
  if [ -f "$SERVER_LOG" ]; then
    # Get the last modified time of the log file
    # Try Linux stat first (-c), fall back to macOS stat (-f)
    local log_mtime=$(stat -c %Y "$SERVER_LOG" 2>/dev/null || stat -f %m "$SERVER_LOG" 2>/dev/null)
    
    # If log was modified more recently than our last check, update last_activity
    if [ "$log_mtime" -gt "$last_activity" ]; then
      last_activity=$(date +%s)
      return 0  # Activity detected
    fi
  fi
  return 1  # No activity
}

# Function to write heartbeat with timestamp
write_heartbeat() {
  echo "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$HEARTBEAT_FILE"
}

# Main monitoring loop
while true; do
  current_time=$(date +%s)
  
  # Check for new activity (updates last_activity if found)
  check_activity
  
  # Calculate time since last activity
  time_since_activity=$((current_time - last_activity))
  
  # If we're within the keepalive window, write heartbeat
  if [ "$time_since_activity" -lt "$KEEPALIVE_SECONDS" ]; then
    write_heartbeat
  fi
  
  # Sleep until next heartbeat interval
  sleep "$HEARTBEAT_INTERVAL"
done
`;
}

/**
 * Start traffic monitoring daemon in codespace
 * 
 * This function:
 * 1. Generates the daemon bash script
 * 2. Writes it to a local temp file
 * 3. Copies it to the codespace /tmp directory using `gh codespace cp`
 * 4. Makes it executable and starts it in the background with nohup
 * 5. Verifies the daemon started by checking for PID file
 * 6. Cleans up local temp file
 * 
 * The daemon runs independently in the codespace and continues monitoring
 * until explicitly stopped with `stopTrafficMonitor()`.
 * 
 * @param options - Traffic monitor configuration
 * @throws Error if daemon fails to start or PID file not created
 * 
 * @example
 * ```typescript
 * await startTrafficMonitor({
 *   codespaceName: 'my-codespace-abc123',
 *   serverPort: 3000,
 *   serverLogPath: '/tmp/sudocode-3000.log',
 *   keepAliveHours: 24,
 *   heartbeatIntervalMinutes: 1
 * });
 * console.log('Traffic monitor daemon started');
 * ```
 */
export async function startTrafficMonitor(
  options: TrafficMonitorOptions
): Promise<void> {
  const { codespaceName, serverPort } = options;
  
  // 1. Generate daemon script
  const scriptContent = generateDaemonScript(options);
  
  // Debug: Log the script content to help diagnose issues
  console.log(`\nGenerated daemon script for port ${serverPort}:`);
  console.log('---START SCRIPT---');
  console.log(scriptContent);
  console.log('---END SCRIPT---\n');
  
  // 2. Write script directly to codespace via SSH using base64 encoding to avoid heredoc issues
  const remoteScriptPath = `/tmp/sudocode-monitor-${serverPort}.sh`;
  
  // Encode script content as base64 to safely transmit through SSH
  const scriptBase64 = Buffer.from(scriptContent).toString('base64');
  
  await execInCodespace(
    codespaceName,
    `echo '${scriptBase64}' | base64 -d > ${remoteScriptPath}`,
    { streamOutput: false, timeout: 10000 }
  );
  
  // 3. Make executable
  await execInCodespace(
    codespaceName,
    `chmod +x ${remoteScriptPath}`,
    { streamOutput: false, timeout: 5000 }
  );
  
  // 4. Start daemon in background using bash -c to ensure it persists after SSH disconnect
  await execInCodespace(
    codespaceName,
    `bash -c 'nohup ${remoteScriptPath} > /tmp/sudocode-monitor-${serverPort}-daemon.log 2>&1 </dev/null & sleep 0.1'`,
    { streamOutput: false, timeout: 10000 }
  );
  
  // 5. Verify daemon is running (check for PID file)
  // Give it a moment to start and write PID file
  await new Promise(resolve => setTimeout(resolve, 2000));
  
  const pidFileExists = await execInCodespace(
    codespaceName,
    `test -f /tmp/sudocode-monitor-${serverPort}.pid && echo "1" || echo "0"`,
    { streamOutput: false }
  );
  
  if (pidFileExists.trim() !== '1') {
    // Get daemon log to help debug
    let daemonLog = '';
    try {
      daemonLog = await execInCodespace(
        codespaceName,
        `cat /tmp/sudocode-monitor-${serverPort}-daemon.log 2>&1 || echo "No log file"`,
        { streamOutput: false }
      );
    } catch (e) {
      daemonLog = 'Could not read daemon log';
    }
    
    throw new Error(`Traffic monitor daemon failed to start: PID file not created\nDaemon log:\n${daemonLog}`);
  }
}

/**
 * Stop traffic monitoring daemon in codespace
 * 
 * Reads the daemon's PID from its PID file and sends a kill signal.
 * Cleans up the PID file after stopping the daemon.
 * 
 * If the daemon is not running or PID file doesn't exist, this function
 * succeeds silently (idempotent operation).
 * 
 * @param codespaceName - Codespace name
 * @param serverPort - Server port number
 * 
 * @example
 * ```typescript
 * await stopTrafficMonitor('my-codespace-abc123', 3000);
 * console.log('Traffic monitor daemon stopped');
 * ```
 */
export async function stopTrafficMonitor(
  codespaceName: string,
  serverPort: number
): Promise<void> {
  const pidFile = `/tmp/sudocode-monitor-${serverPort}.pid`;
  
  // Read PID and kill process, remove PID file
  // Use || true to make the command succeed even if process doesn't exist
  await execInCodespace(
    codespaceName,
    `[ -f ${pidFile} ] && kill $(cat ${pidFile}) && rm ${pidFile} || true`,
    { streamOutput: false }
  );
}

/**
 * Check if traffic monitor is running
 * 
 * Checks both that:
 * 1. The PID file exists
 * 2. The process is actually running (via `ps -p <pid>`)
 * 
 * This ensures we detect stale PID files where the daemon has crashed
 * or been killed externally.
 * 
 * @param codespaceName - Codespace name
 * @param serverPort - Server port number
 * @returns True if daemon is running, false otherwise
 * 
 * @example
 * ```typescript
 * const isRunning = await isTrafficMonitorRunning('my-codespace-abc123', 3000);
 * if (isRunning) {
 *   console.log('Traffic monitor is active');
 * } else {
 *   console.log('Traffic monitor is not running');
 * }
 * ```
 */
export async function isTrafficMonitorRunning(
  codespaceName: string,
  serverPort: number
): Promise<boolean> {
  try {
    const pidFile = `/tmp/sudocode-monitor-${serverPort}.pid`;
    
    // Check if PID file exists AND process is running
    const result = await execInCodespace(
      codespaceName,
      `[ -f ${pidFile} ] && ps -p $(cat ${pidFile}) > /dev/null && echo "1" || echo "0"`,
      { streamOutput: false }
    );
    
    return result.trim() === '1';
  } catch {
    // If command fails (e.g., codespace unreachable), assume not running
    return false;
  }
}
