
FROM python:3.11-slim-bullseye

RUN apt-get update && apt-get install -y gcc python3-dev

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV ENV staging

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--log-level", "info", "--port", "8080"]
