/**
 * Coder Keepalive Daemon
 *
 * Generates a keepalive script that monitors sudocode activity and
 * extends the workspace deadline using `coder bump`.
 *
 * Key difference from Codespaces: Coder uses explicit deadline extension
 * via `coder bump` rather than relying on activity detection.
 *
 * @see s-6q31 - Coder Provider Implementation specification
 * @see i-mucf - Implement Coder keepalive daemon issue
 */

// ============================================================================
// Script Generation
// ============================================================================

/**
 * Generate a keepalive daemon script for Coder workspaces.
 *
 * The script monitors a log file for recent activity and extends the
 * workspace deadline when activity is detected within the idle timeout.
 *
 * @param port - Sudocode server port (used for log file name)
 * @param idleTimeoutMinutes - Minutes of inactivity before stopping keepalive bumps
 * @param bumpHours - Hours to extend the deadline each bump (default: 2)
 * @param checkIntervalSeconds - Seconds between activity checks (default: 30)
 */
export function generateKeepaliveScript(
  port: number,
  idleTimeoutMinutes: number,
  bumpHours = 2,
  checkIntervalSeconds = 30
): string {
  const idleTimeoutSeconds = idleTimeoutMinutes * 60;

  return `#!/bin/bash
# ============================================================================
# Sudocode Keepalive Daemon for Coder
# ============================================================================
#
# This daemon monitors sudocode activity and extends the workspace deadline
# to prevent auto-stop during active usage.
#
# It checks the sudocode log file modification time and runs 'coder bump'
# when activity is detected within the idle timeout.
#
# Environment:
#   CODER_WORKSPACE_NAME - Set automatically by Coder agent
#
# Generated by: sudopod keepalive generator
# ============================================================================

set -e

# Configuration
LOG_FILE="/tmp/sudocode-${port}.log"
IDLE_TIMEOUT_SECONDS=${idleTimeoutSeconds}
CHECK_INTERVAL=${checkIntervalSeconds}
BUMP_HOURS=${bumpHours}

# Logging function
log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] [keepalive] $*"
}

# Get file modification time (cross-platform)
# Linux uses 'stat -c %Y', macOS uses 'stat -f %m'
get_mtime() {
  local file="$1"
  if stat -c %Y "$file" 2>/dev/null; then
    return
  fi
  # Fallback to macOS format
  stat -f %m "$file" 2>/dev/null || echo "0"
}

log "Starting keepalive daemon"
log "  Log file: $LOG_FILE"
log "  Idle timeout: ${idleTimeoutSeconds} seconds (${idleTimeoutMinutes} minutes)"
log "  Check interval: $CHECK_INTERVAL seconds"
log "  Bump duration: $BUMP_HOURS hours"
log "  Workspace: \${CODER_WORKSPACE_NAME:-unknown}"

# Main loop
while true; do
  sleep $CHECK_INTERVAL

  # Check if log file exists
  if [ -f "$LOG_FILE" ]; then
    LAST_MODIFIED=$(get_mtime "$LOG_FILE")
    NOW=$(date +%s)
    IDLE_SECONDS=$((NOW - LAST_MODIFIED))

    if [ $IDLE_SECONDS -lt $IDLE_TIMEOUT_SECONDS ]; then
      # Active - bump workspace deadline
      if [ -n "$CODER_WORKSPACE_NAME" ]; then
        if coder bump "$CODER_WORKSPACE_NAME" "\${BUMP_HOURS}h" 2>/dev/null; then
          log "Bumped workspace deadline by $BUMP_HOURS hours (idle: \${IDLE_SECONDS}s)"
        fi
      fi
    fi
  fi
done
`;
}

/**
 * Generate the script path for the keepalive daemon.
 */
export function getKeepaliveScriptPath(): string {
  return '/tmp/sudocode-keepalive.sh';
}

/**
 * Generate a PID file path for the keepalive daemon.
 */
export function getKeepalivePidPath(): string {
  return '/tmp/sudocode-keepalive.pid';
}

/**
 * Generate a command to start the keepalive daemon in the background.
 *
 * @param scriptPath - Path to the keepalive script
 * @param pidPath - Path to store the PID
 */
export function generateStartCommand(
  scriptPath = getKeepaliveScriptPath(),
  pidPath = getKeepalivePidPath()
): string {
  return `nohup ${scriptPath} > /tmp/sudocode-keepalive.log 2>&1 & echo $! > ${pidPath}`;
}

/**
 * Generate a command to stop the keepalive daemon.
 *
 * @param pidPath - Path to the PID file
 */
export function generateStopCommand(
  pidPath = getKeepalivePidPath()
): string {
  return `if [ -f "${pidPath}" ]; then kill $(cat "${pidPath}") 2>/dev/null || true; rm -f "${pidPath}"; fi`;
}

/**
 * Generate a command to check if the keepalive daemon is running.
 *
 * @param pidPath - Path to the PID file
 */
export function generateCheckCommand(
  pidPath = getKeepalivePidPath()
): string {
  return `if [ -f "${pidPath}" ] && kill -0 $(cat "${pidPath}") 2>/dev/null; then echo "running"; else echo "stopped"; fi`;
}
